#Biopython mechanisms for dealing with sequences, the Seq object
from Bio.Seq import Seq
my_seq=Seq("AGTACACTGGT")
#The Seq object differs from the Python string in the methods it supports
print(my_seq)
print(my_seq.complement()) '''A complementary DNA sequence is generated by pairing nitrogenous bases to a template strand according to specific rules: A pairs with T (Adenine-Thymine) and C pairs with G (Cytosine-Guanine). '''
